### ISSUE TITLE
Create email account

### ISSUE THREAD

**Issue by wouterbeek** [Vrijheid-Zonder-Maar/vzm-backend#24]
E.g., `info@vrijheidzondermaar.nl`.

**Comment by charifmews** [comment]
Depends were you registered the domain name @andreaspeijer, I know that namecheap has free email forwarding. 

Free version independent of your domain registrar which looks good is (don't know how trustworthy it is, but we can give it a try):

http://improvmx.com/

**Comment by charifmews** [comment]
Assignee me again if you want to give me the password for the domain registrar (would be logical not to do this because the less people have access, the better it is from security perspective) or if you have troubles with the DNS settings and need help/alternatives.

**Comment by wouterbeek** [comment]
Mails whose sender matches `*@vrijheidzondermaar.nl` now forward to Andrea's GMail.
