### ISSUE TITLE
After paying Sohosted many things have stoppen working

### ISSUE THREAD

**Issue by wouterbeek** [Vrijheid-Zonder-Maar/vzm-backend#37]
1. Email still does not work.
  2. `www.` refers to Sohosted.
  3. Google login is broken

**Comment by andreaspeijer** [comment]
https://www.sohosted.com/klantenservice/faq/e-mail/hoe-maak-ik-een-e-mailadres-aan/

2016-01-07 17:05 GMT+01:00 Wouter Beek <notifications@github.com>:

**Comment by andreaspeijer** [comment]
Van Charif. Zijn advies is om de tekst breder te maken zodat het
makkelijker leest.

2016-02-20 15:42 GMT+01:00 Wouter Beek <notifications@github.com>:
